import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Navbar2 from "./components/Navbar2";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Navbar2 />
        {children}
      </body>
    </html>
  );
}
